/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppearancePanel: typeof import('./src/components/settings/AppearancePanel.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImageViewer: typeof import('element-plus/es')['ElImageViewer']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    LoginForm: typeof import('./src/components/auth/LoginForm.vue')['default']
    NotificationPanel: typeof import('./src/components/settings/NotificationPanel.vue')['default']
    ProfilePanel: typeof import('./src/components/settings/ProfilePanel.vue')['default']
    RecentActivity: typeof import('./src/components/dashboard/RecentActivity.vue')['default']
    RecentUploads: typeof import('./src/components/dashboard/RecentUploads.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityPanel: typeof import('./src/components/settings/SecurityPanel.vue')['default']
    StarryBackground: typeof import('./src/components/StarryBackground.vue')['default']
    StatCards: typeof import('./src/components/dashboard/StatCards.vue')['default']
    SystemPanel: typeof import('./src/components/settings/SystemPanel.vue')['default']
    TrendChart: typeof import('./src/components/dashboard/TrendChart.vue')['default']
    UserEditDialog: typeof import('./src/components/users/UserEditDialog.vue')['default']
    UserSearchForm: typeof import('./src/components/users/UserSearchForm.vue')['default']
    UserTable: typeof import('./src/components/users/UserTable.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AppearancePanel: (typeof import('./src/components/settings/AppearancePanel.vue'))['default'];
  const ElAside: (typeof import('element-plus/es'))['ElAside'];
  const ElAvatar: (typeof import('element-plus/es'))['ElAvatar'];
  const ElBadge: (typeof import('element-plus/es'))['ElBadge'];
  const ElBreadcrumb: (typeof import('element-plus/es'))['ElBreadcrumb'];
  const ElBreadcrumbItem: (typeof import('element-plus/es'))['ElBreadcrumbItem'];
  const ElButton: (typeof import('element-plus/es'))['ElButton'];
  const ElButtonGroup: (typeof import('element-plus/es'))['ElButtonGroup'];
  const ElCard: (typeof import('element-plus/es'))['ElCard'];
  const ElCheckbox: (typeof import('element-plus/es'))['ElCheckbox'];
  const ElCol: (typeof import('element-plus/es'))['ElCol'];
  const ElConfigProvider: (typeof import('element-plus/es'))['ElConfigProvider'];
  const ElContainer: (typeof import('element-plus/es'))['ElContainer'];
  const ElDialog: (typeof import('element-plus/es'))['ElDialog'];
  const ElDivider: (typeof import('element-plus/es'))['ElDivider'];
  const ElDropdown: (typeof import('element-plus/es'))['ElDropdown'];
  const ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem'];
  const ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu'];
  const ElForm: (typeof import('element-plus/es'))['ElForm'];
  const ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
  const ElHeader: (typeof import('element-plus/es'))['ElHeader'];
  const ElIcon: (typeof import('element-plus/es'))['ElIcon'];
  const ElImageViewer: (typeof import('element-plus/es'))['ElImageViewer'];
  const ElInput: (typeof import('element-plus/es'))['ElInput'];
  const ElMain: (typeof import('element-plus/es'))['ElMain'];
  const ElMenu: (typeof import('element-plus/es'))['ElMenu'];
  const ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
  const ElOption: (typeof import('element-plus/es'))['ElOption'];
  const ElPagination: (typeof import('element-plus/es'))['ElPagination'];
  const ElRadio: (typeof import('element-plus/es'))['ElRadio'];
  const ElRadioButton: (typeof import('element-plus/es'))['ElRadioButton'];
  const ElRadioGroup: (typeof import('element-plus/es'))['ElRadioGroup'];
  const ElRow: (typeof import('element-plus/es'))['ElRow'];
  const ElSelect: (typeof import('element-plus/es'))['ElSelect'];
  const ElSwitch: (typeof import('element-plus/es'))['ElSwitch'];
  const ElTable: (typeof import('element-plus/es'))['ElTable'];
  const ElTableColumn: (typeof import('element-plus/es'))['ElTableColumn'];
  const ElTag: (typeof import('element-plus/es'))['ElTag'];
  const ElTimeline: (typeof import('element-plus/es'))['ElTimeline'];
  const ElTimelineItem: (typeof import('element-plus/es'))['ElTimelineItem'];
  const ElUpload: (typeof import('element-plus/es'))['ElUpload'];
  const LoginForm: (typeof import('./src/components/auth/LoginForm.vue'))['default'];
  const NotificationPanel: (typeof import('./src/components/settings/NotificationPanel.vue'))['default'];
  const ProfilePanel: (typeof import('./src/components/settings/ProfilePanel.vue'))['default'];
  const RecentActivity: (typeof import('./src/components/dashboard/RecentActivity.vue'))['default'];
  const RecentUploads: (typeof import('./src/components/dashboard/RecentUploads.vue'))['default'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const SecurityPanel: (typeof import('./src/components/settings/SecurityPanel.vue'))['default'];
  const StarryBackground: (typeof import('./src/components/StarryBackground.vue'))['default'];
  const StatCards: (typeof import('./src/components/dashboard/StatCards.vue'))['default'];
  const SystemPanel: (typeof import('./src/components/settings/SystemPanel.vue'))['default'];
  const TrendChart: (typeof import('./src/components/dashboard/TrendChart.vue'))['default'];
  const UserEditDialog: (typeof import('./src/components/users/UserEditDialog.vue'))['default'];
  const UserSearchForm: (typeof import('./src/components/users/UserSearchForm.vue'))['default'];
  const UserTable: (typeof import('./src/components/users/UserTable.vue'))['default'];
}
